repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args:
          - -d
          - '{extends: default, rules: {line-length: {max: 100}}}'
        files: ^(docker-compose\.yaml|config/.*\.ya?ml)$
